/-
# The claims of the paper programs, as statements about the executable semantics

Generated by `scripts/gen_lean_claims.py` from the IR of the programs under
`examples/papers/` (`tools/claims/*.ir.json`). Do not edit. For each
program: its session program (after the workload's arrival delay and the
`init` sets that do not draw), its deployment, the family of workloads its
claims quantify over, and each claim as an `Exec.EveryIteration`,
`Exec.SomeIteration` or `Exec.AtEnd` statement (`Serq/Claim.lean`). The
proofs are in `Serq/Papers/`; `Serq/ClaimsProved.lean` checks that every
claim has one.
-/
import Serq.Claim

set_option maxRecDepth 100000

namespace SerqLang
namespace Claims

open Exec

/-! ## `examples/papers/bari_rad.sq` -/

namespace BariRad

/-- The session program of `examples/papers/bari_rad.sq`. Attributes: 0 = cached, 1 = serial, 2 = turn_no, 3 = new, 4 = out, 5 = think, 6 = more, 7 = forced, 8 = computed, 9 = t0, 10 = vp, 11 = vd, 12 = arrive. Observations: 0 = response. -/
def prog : Prog := [route|
  run 1 (x.attr 12);
  set 9 = x.now;
  run 0 prefill (x.attr 10);
  run 0 decode (x.attr 11);
  observe 0 = x.now - (x.attr 9);
  stop]

def deployment : Deployment :=
  ⟨[], 128, 128, none, fun st => 4000 * ((st.tokens + 127) / 128) + 5 * st.tokens, some fun e => (if ((e.decoders ≥ 128) ∨ (e.decoders = e.residents)) then e.decoding else (if (e.decoding ≠ 0) then 0 else 1))⟩

/-- The workloads the claims of `bari_rad.sq` quantify over. -/
def family (w : Workload) : Prop :=
    w.init.length ≤ 500 ∧
    w.turns = [] ∧
    w.turnSlot = none ∧
    w.computedSlot = some 8 ∧
    ∀ i < w.init.length, (((w.attr i 10) = (128 * ((w.attr i 10) / 128))))

/-- `claim token_rate` of `bari_rad.sq`. -/
def token_rate : Prop :=
  EveryIteration deployment family prog fun r => ((r.served * 4640) ≤ (128 * r.start))

/-- `claim optimal_tiling` of `bari_rad.sq`. -/
def optimal_tiling : Prop :=
  EveryIteration deployment family prog fun r => ((r.stats.tokens = 128) ∨ (r.stats.decoders = r.residents))

end BariRad

/-! ## `examples/papers/dai_fastertransformer.sq` -/

namespace DaiFastertransformer

/-- The session program of `examples/papers/dai_fastertransformer.sq`. Attributes: 0 = cached, 1 = serial, 2 = turn_no, 3 = new, 4 = out, 5 = think, 6 = more, 7 = forced, 8 = computed, 9 = t0, 10 = arrive. Observations: 0 = response. -/
def prog : Prog := [route|
  run 1 (x.attr 10);
  set 9 = x.now;
  run 0 prefill (290);
  run 0 decode (990);
  observe 0 = x.now - (x.attr 9);
  stop]

def deployment : Deployment :=
  ⟨[], 128, 0, none, fun st => 1128 + 3547 * ((st.tokens + 127) / 128), some fun e => (if (e.decoders > 0) then e.decoding else (if (e.decoding ≠ 0) then 0 else 1))⟩

/-- The workloads the claims of `dai_fastertransformer.sq` quantify over. -/
def family (w : Workload) : Prop :=
    w.init.length ≤ 500 ∧
    w.turns = [] ∧
    w.turnSlot = none ∧
    w.computedSlot = some 8 ∧
    ∀ i < w.init.length, w.attr i 10 = (i + 1) * 46750

/-- `claim not_work_conserving` of `dai_fastertransformer.sq`. -/
def not_work_conserving : Prop :=
  SomeIteration deployment family prog fun r => ((r.demand ≥ 128) ∧ (r.stats.tokens < 128))

/-- `claim token_rate` of `dai_fastertransformer.sq`. -/
def token_rate : Prop :=
  EveryIteration deployment family prog fun r => ((r.served * 4675) ≤ (128 * r.start))

end DaiFastertransformer

/-! ## `examples/papers/dai_sarathi.sq` -/

namespace DaiSarathi

/-- The session program of `examples/papers/dai_sarathi.sq`. Attributes: 0 = cached, 1 = serial, 2 = turn_no, 3 = new, 4 = out, 5 = think, 6 = more, 7 = forced, 8 = computed, 9 = t0, 10 = arrive. Observations: 0 = response. -/
def prog : Prog := [route|
  run 1 (x.attr 10);
  set 9 = x.now;
  run 0 prefill (290);
  run 0 decode (990);
  observe 0 = x.now - (x.attr 9);
  stop]

def deployment : Deployment :=
  ⟨[], 128, 0, none, fun st => 1128 + 3547 * ((st.tokens + 127) / 128), none⟩

/-- The workloads the claims of `dai_sarathi.sq` quantify over. -/
def family (w : Workload) : Prop :=
    w.init.length ≤ 500 ∧
    w.turns = [] ∧
    w.turnSlot = none ∧
    w.computedSlot = some 8 ∧
    ∀ i < w.init.length, w.attr i 10 = (i + 1) * 46750

/-- `claim work_conserving` of `dai_sarathi.sq`. -/
def work_conserving : Prop :=
  EveryIteration deployment family prog fun r => ((r.demand < 128) ∨ (r.stats.tokens = 128))

/-- `claim token_rate` of `dai_sarathi.sq`. -/
def token_rate : Prop :=
  EveryIteration deployment family prog fun r => ((r.served * 4675) ≤ (128 * r.start))

end DaiSarathi

/-! ## `examples/papers/kong_svf.sq` -/

namespace KongSvf

/-- The session program of `examples/papers/kong_svf.sq`. Attributes: 0 = cached, 1 = serial, 2 = turn_no, 3 = new, 4 = out, 5 = think, 6 = more, 7 = forced, 8 = computed, 9 = s, 10 = o. Observations: 0 = out, 1 = vol, 2 = latency. -/
def prog : Prog := [route|
  observe 0 = x.attr 10;
  observe 1 = ((x.attr 9) * (x.attr 10)) + ((((x.attr 10) * (x.attr 10)) + (x.attr 10)) / 2);
  hold 0 ((x.attr 9) + (x.attr 10)) {
    run 0 decode (x.attr 10);
    done
  };
  observe 2 = x.now;
  stop]

def deployment : Deployment :=
  ⟨[⟨20000, 1, false, some fun x => ((x.attr 9) * (x.attr 10)) + ((((x.attr 10) * (x.attr 10)) + (x.attr 10)) / 2)⟩], 1000000, 0, none, fun _ => 1, none⟩

/-- The workloads the claims of `kong_svf.sq` quantify over. -/
def family (w : Workload) : Prop :=
    w.init.length ≤ 500 ∧
    w.turns = [] ∧
    w.turnSlot = none ∧
    w.computedSlot = some 8 ∧
    ∀ i < w.init.length, (((((w.attr i 9) + (w.attr i 10)) ≤ 2500) ∧ ((w.attr i 10) ≥ 1)))

/-- `claim queueing_bound` of `kong_svf.sq`. -/
def queueing_bound : Prop :=
  AtEnd deployment family prog fun m => ((17500 * ((Exec.total m 2) - (Exec.total m 0))) ≤ (2 * ((Exec.prefixTotal (Exec.values m 1)) - (Exec.total m 1))))

end KongSvf

end Claims
end SerqLang
