/-
# Every claim of the paper programs is proved

Generated by `scripts/gen_lean_claims.py`. Do not edit. Each line states a
claim of `Serq/Claims.lean` and names its proof in `Serq/Papers/`: the build
fails if a claim has no proof, or if a proof proves something else than
what the program now claims.
-/
import Serq.Claims
import Serq.Papers

namespace SerqLang
namespace ClaimsProved
example : Claims.BariRad.token_rate := Papers.BariRad.token_rate
example : Claims.BariRad.optimal_tiling := Papers.BariRad.optimal_tiling
example : Claims.DaiFastertransformer.not_work_conserving := Papers.DaiFastertransformer.not_work_conserving
example : Claims.DaiFastertransformer.token_rate := Papers.DaiFastertransformer.token_rate
example : Claims.DaiSarathi.work_conserving := Papers.DaiSarathi.work_conserving
example : Claims.DaiSarathi.token_rate := Papers.DaiSarathi.token_rate
example : Claims.DaiSarathi.bounded := Papers.DaiSarathi.bounded
example : Claims.KongSvf.queueing_bound := Papers.KongSvf.queueing_bound

end ClaimsProved
end SerqLang
