//! A `Figure` as a TikZ picture.
//!
//! The backend for a figure inside a LaTeX document: TikZ source the
//! document can `\input` - an image inherits neither the document's fonts
//! nor its rules, and does not diff.
//!
//! The output needs `\usepackage{tikz}` and nothing else.

use std::fmt::Write as _;

use crate::view::figure::{Anchor, BoxStyle, EdgeStyle, Figure, Item, StationKind};

/// LaTeX-escape a label. serQ expressions carry `_`, `^`, `~`, `<` and `&`.
fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\textbackslash{}"),
            '{' => out.push_str("\\{"),
            '}' => out.push_str("\\}"),
            '$' => out.push_str("\\$"),
            '&' => out.push_str("\\&"),
            '#' => out.push_str("\\#"),
            '_' => out.push_str("\\_"),
            '%' => out.push_str("\\%"),
            '^' => out.push_str("\\textasciicircum{}"),
            '~' => out.push_str("\\textasciitilde{}"),
            '<' => out.push_str("\\textless{}"),
            '>' => out.push_str("\\textgreater{}"),
            _ => out.push(c),
        }
    }
    out
}

fn n(x: f64) -> String {
    let r = (x * 100.0).round() / 100.0;
    if r == r.trunc() {
        format!("{}", r as i64)
    } else {
        format!("{r}")
    }
}

fn p(x: f64, y: f64) -> String {
    format!("({},{})", n(x), n(y))
}

fn box_style(s: BoxStyle) -> &'static str {
    match s {
        BoxStyle::Solid => "seqsolid",
        BoxStyle::Cached => "seqcached",
        BoxStyle::Enclosure => "seqenclosure",
        BoxStyle::Flow => "seqrail",
        BoxStyle::Instance => "seqinstance",
        BoxStyle::Frame => "seqframe",
    }
}

fn edge_style(s: EdgeStyle) -> &'static str {
    match s {
        EdgeStyle::Flow => "seqflow",
        EdgeStyle::Back => "seqback",
        EdgeStyle::Relation => "seqrelation",
    }
}

const PREAMBLE: &str = r#"% Generated by `serq draw --format tikz`. Do not edit by hand.
% Requires \usepackage{tikz}.
\definecolor{seqink}{HTML}{1D2021}
\definecolor{seqdim}{HTML}{6B7280}
\definecolor{seqline}{HTML}{4B5563}
\definecolor{seqfill}{HTML}{EEF2F5}
\definecolor{seqtint}{HTML}{D8E6E4}
\definecolor{seqcache}{HTML}{E6E2DA}
\definecolor{seqpanel}{HTML}{F5F7F9}
"#;

const STYLES: &str = r#"x=1pt, y=-1pt, line cap=round, line join=round,
  every node/.style={inner sep=0pt, outer sep=0pt, text=seqink},
  seqsolid/.style={draw=seqline, fill=seqfill, line width=.8pt},
  seqcached/.style={draw=none, fill=seqcache},
  seqinstance/.style={draw=seqline, fill=seqpanel, line width=.8pt},
  seqframe/.style={draw=seqline, line width=.8pt},
  seqenclosure/.style={draw=seqdim, line width=.7pt, dash pattern=on 4.5pt off 3pt},
  seqstation/.style={draw=seqline, fill=seqtint, line width=.9pt},
  seqcell/.style={draw=seqline, fill=white, line width=.5pt},
  seqrail/.style={draw=seqline, line width=.7pt},
  seqflow/.style={draw=seqline, line width=.9pt, ->},
  seqback/.style={draw=seqline, line width=.8pt, dash pattern=on 3pt off 2.5pt, ->},
  seqrelation/.style={draw=seqdim, line width=.7pt, dash pattern=on 1.5pt off 2.5pt, ->}"#;

/// Render a figure as a `tikzpicture`, with the colours it needs.
pub fn render(f: &Figure) -> String {
    let mut s = String::from(PREAMBLE);
    let _ = writeln!(s, "\\begin{{tikzpicture}}[{STYLES}]");

    for item in &f.items {
        match item {
            Item::Box { rect, style, round } => {
                let r = if *round > 0.0 {
                    format!("rounded corners={}pt, ", n(*round))
                } else {
                    String::new()
                };
                let _ = writeln!(
                    s,
                    "  \\draw[{r}{}] {} rectangle {};",
                    box_style(*style),
                    p(rect.x, rect.y),
                    p(rect.right(), rect.bottom())
                );
            }
            Item::Station { rect, kind, text } => {
                let c = rect.centre();
                match kind {
                    StationKind::Fifo | StationKind::Ps => {
                        let _ = writeln!(
                            s,
                            "  \\draw[seqstation] {} circle ({}pt);",
                            p(c.x, c.y),
                            n(rect.h.min(rect.w) / 2.0)
                        );
                    }
                    StationKind::Delay => {
                        let _ = writeln!(
                            s,
                            "  \\draw[seqstation, rounded corners=8pt] {} rectangle {};",
                            p(rect.x, rect.y),
                            p(rect.right(), rect.bottom())
                        );
                        if let Some(pts) = crate::view::figure::density(text, *rect) {
                            let path: Vec<String> = pts.iter().map(|q| p(q.x, q.y)).collect();
                            let _ = writeln!(s, "  \\draw[seqrail] {};", path.join(" -- "));
                        } else {
                            // a duration that is no distribution: infinitely
                            // many servers, as the lecture draws a delay
                            for k in 0..5 {
                                let x = rect.x + rect.w * (k as f64 + 1.0) / 6.0;
                                let _ =
                                    writeln!(s, "  \\draw[seqcell] {} circle (4pt);", p(x, c.y));
                            }
                        }
                    }
                    StationKind::Decision => {
                        let r = rect.h.min(rect.w) / 2.0;
                        let _ = writeln!(
                            s,
                            "  \\draw[seqstation] {} -- {} -- {} -- {} -- cycle;",
                            p(c.x, c.y - r),
                            p(c.x + r, c.y),
                            p(c.x, c.y + r),
                            p(c.x - r, c.y)
                        );
                    }
                    StationKind::Step => {
                        let _ = writeln!(
                            s,
                            "  \\draw[seqstation, rounded corners=3pt] {} rectangle {};",
                            p(rect.x, rect.y),
                            p(rect.right(), rect.bottom())
                        );
                        let (bx, by, bw, bh) =
                            (rect.x + 8.0, rect.bottom() - 13.0, rect.w - 16.0, 6.0);
                        let _ = writeln!(
                            s,
                            "  \\draw[seqcell] {} rectangle {};",
                            p(bx, by),
                            p(bx + bw, by + bh)
                        );
                        let _ = writeln!(
                            s,
                            "  \\draw[seqsolid] {} rectangle {};",
                            p(bx, by),
                            p(bx + bw * 0.62, by + bh)
                        );
                    }
                }
                if !text.is_empty() {
                    // under the budget bar, or the density
                    let dy = match kind {
                        StationKind::Step => -8.0,
                        StationKind::Delay => 15.0,
                        _ => 0.0,
                    };
                    let _ = writeln!(
                        s,
                        "  \\node[anchor=center] at {} {{\\ttfamily\\footnotesize {}}};",
                        p(c.x, c.y + dy),
                        esc(text)
                    );
                }
            }
            Item::Queue { rect, cells } => {
                let _ = writeln!(
                    s,
                    "  \\draw[seqrail] {} -- {};",
                    p(rect.x, rect.y),
                    p(rect.right(), rect.y)
                );
                let _ = writeln!(
                    s,
                    "  \\draw[seqrail] {} -- {};",
                    p(rect.x, rect.bottom()),
                    p(rect.right(), rect.bottom())
                );
                let cw = rect.w / (*cells as f64 + 0.5);
                for k in 0..*cells {
                    let x = rect.x + cw * (k as f64 + 0.25);
                    let _ = writeln!(
                        s,
                        "  \\draw[seqcell] {} rectangle {};",
                        p(x, rect.y + 2.0),
                        p(x + cw * 0.7, rect.bottom() - 2.0)
                    );
                }
            }
            Item::Drum { rect } => {
                // y grows downwards here: the arc from 180 to 0 passes 90,
                // the near side of the bottom
                let (rx, ry) = (rect.w / 2.0, (rect.h / 5.0).min(4.0));
                let _ = writeln!(
                    s,
                    "  \\draw[seqcell] {} -- {} arc[start angle=180, end angle=0, x radius={}, y radius={}] -- {} -- cycle;",
                    p(rect.x, rect.y + ry),
                    p(rect.x, rect.bottom() - ry),
                    n(rx),
                    n(ry),
                    p(rect.right(), rect.y + ry)
                );
                let _ = writeln!(
                    s,
                    "  \\draw[seqcell] {} ellipse [x radius={}, y radius={}];",
                    p(rect.centre().x, rect.y + ry),
                    n(rx),
                    n(ry)
                );
            }
            Item::Edge { pts, style, arrow } => {
                let path: Vec<String> = pts.iter().map(|q| p(q.x, q.y)).collect();
                let st = edge_style(*style);
                let opts = if *arrow {
                    st.to_string()
                } else {
                    format!("{st}, -")
                };
                let _ = writeln!(s, "  \\draw[{opts}] {};", path.join(" -- "));
            }
            Item::Text {
                at,
                text,
                anchor,
                size,
                dim,
            } => {
                let a = match anchor {
                    Anchor::Start => "base west",
                    Anchor::Middle => "base",
                    Anchor::End => "base east",
                };
                let sz = match size {
                    crate::view::figure::TextSize::Title => "\\small",
                    crate::view::figure::TextSize::Normal => "\\footnotesize",
                    crate::view::figure::TextSize::Small => "\\scriptsize",
                };
                let colour = if *dim { "text=seqdim, " } else { "" };
                let _ = writeln!(
                    s,
                    "  \\node[{colour}anchor={a}] at {} {{\\ttfamily{sz} {}}};",
                    p(at.x, at.y),
                    esc(text)
                );
            }
        }
    }
    s.push_str("\\end{tikzpicture}\n");
    s
}
