/-
# Every claim of the paper programs is proved

Generated by `scripts/gen_lean_claims.py`. Do not edit. Each line states a
claim of `Serq/Claims.lean` and names its proof in `examples/papers/`: the build
fails if a claim has no proof, or if a proof proves something else than
what the program now claims.
-/
import Serq.Claims
import papers.Bari
import papers.BariChain
import papers.BariNodes
import papers.BariPoisson
import papers.BariProgram
import papers.BariRecurrent
import papers.BariSim
import papers.BariStable
import papers.Dai
import papers.DaiBounded
import papers.DaiChain
import papers.DaiPoisson
import papers.DaiProgram
import papers.DaiRecurrent
import papers.DaiSim
import papers.DaiStable
import papers.Kong
import papers.KongMath
import papers.KongPoisson

namespace SerqLang
namespace ClaimsProved
example : Claims.BariRad.token_rate := Papers.BariRad.token_rate
example : Claims.BariRad.optimal_tiling := Papers.BariRad.optimal_tiling
example : Claims.DaiFastertransformer.not_work_conserving := Papers.DaiFastertransformer.not_work_conserving
example : Claims.DaiFastertransformer.token_rate := Papers.DaiFastertransformer.token_rate
example : Claims.DaiSarathi.work_conserving := Papers.DaiSarathi.work_conserving
example : Claims.DaiSarathi.token_rate := Papers.DaiSarathi.token_rate
example : Claims.DaiSarathi.bounded := Papers.DaiSarathi.bounded
example : Claims.KongSvf.queueing_bound := Papers.KongSvf.queueing_bound

end ClaimsProved
end SerqLang
