/-
# seQ: formal models of LLM serving systems

`SeQ.Route` (syntax of ROUTE programs and the pool semantics),
`SeQ.RouteExec` (executable semantics on the step clock),
`SeQ.RouteOracle` (the vLLM scheduler scenarios as theorems; generated by
`scripts/gen_oracle.py`), `SeQ.RouteServe` (serving order of a step
engine).
-/
import SeQ.Route
import SeQ.RouteExec
import SeQ.RouteOracle
import SeQ.RouteServe
