/-
# serQ in Lean

The formal model of serQ (`docs/lean.md`): the syntax and the pool
semantics (`Serq.Core`), the executable semantics of the step-engine
fragment (`Serq.Exec`), the serving order of a step engine (`Serq.Serve`),
and the vLLM scheduler scenarios of `tools/oracle/` as theorems about the
serQ programs they were compiled from (`Serq.Oracle`, generated by
`scripts/gen_lean_oracle.py`), the regressions against the interpreter
(`Serq.Regress`, generated from `tests/lean-regress/`), and the core of
the regeneration conjecture: dead cache entries are irrelevant to the live
ones under LRU (`Serq.Regen`). Claims: what a program says about its own
paths (`Serq.Claim`), the invariants every path keeps (`Serq.Inv`,
`Serq.Work`), the claims of the paper programs under `examples/papers/` as
statements (`Serq.Claims`, generated by `scripts/gen_lean_claims.py`), their
proofs (`Serq.Papers`), and the check that every claim has one
(`Serq.ClaimsProved`). Foster's criterion on a kernel of finite support,
from its first-step equations, without a path measure (`Serq.Foster`), and
a program with random arrivals as such a kernel (`Serq.Chain`), and positive
recurrence from it (`Serq.Recurrence`).
-/
import Serq.Core
import Serq.Exec
import Serq.Serve
import Serq.Fill
import Serq.Oracle
import Serq.Regress
import Serq.Regen
import Serq.Claim
import Serq.Inv
import Serq.Steps
import Serq.Work
import Serq.Claims
import Serq.Papers
import Serq.ClaimsProved
import Serq.Foster
import Serq.Chain
import Serq.Recurrence
