/-
# serQ in Lean

The formal model of serQ (`docs/lean.md`): the syntax and the pool
semantics (`Serq.Core`), the executable semantics of the step-engine
fragment (`Serq.Exec`), the serving order of a step engine (`Serq.Serve`),
and the vLLM scheduler scenarios of `tools/oracle/` as theorems about the
serQ programs they were compiled from (`Serq.Oracle`, generated by
`scripts/gen_lean_oracle.py`), the regressions against the interpreter
(`Serq.Regress`, generated from `tests/lean-regress/`), and the core of
the regeneration conjecture: dead cache entries are irrelevant to the live
ones under LRU (`Serq.Regen`).
-/
import Serq.Core
import Serq.Exec
import Serq.Serve
import Serq.Fill
import Serq.Oracle
import Serq.Regress
import Serq.Regen
