/-
# serQ in Lean

The formal model of serQ (`docs/lean.md`): the syntax and the pool
semantics (`Serq.Core`), the executable semantics of the step-engine
fragment (`Serq.Exec`), the serving order of a step engine (`Serq.Serve`),
and the vLLM scheduler scenarios of `tools/oracle/` as theorems about the
serQ programs they were compiled from (`Serq.Oracle`, generated by
`scripts/gen_lean_oracle.py`), and the regressions differential testing
found (`Serq.Regress`).
-/
import Serq.Core
import Serq.Exec
import Serq.Serve
import Serq.Oracle
import Serq.Regress
