//! A `Figure` as a TikZ picture.
//!
//! This is the backend that matters for the lecture notes: `fig:deployment`
//! of `serving-queue-theory` is a `tikzpicture` inside `lecture1.tex`, and a
//! generated figure replaces it only if the generated artefact is LaTeX
//! source the document can `\input` — an image inherits neither the
//! document's fonts nor its rules, and does not diff.
//!
//! The output needs `\usepackage{tikz}` and nothing else.

use std::fmt::Write as _;

use crate::figure::{Anchor, BoxStyle, EdgeStyle, Figure, Item, StationKind};

/// LaTeX-escape a label. seQ expressions carry `_`, `^`, `~`, `<` and `&`.
fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\textbackslash{}"),
            '{' => out.push_str("\\{"),
            '}' => out.push_str("\\}"),
            '$' => out.push_str("\\$"),
            '&' => out.push_str("\\&"),
            '#' => out.push_str("\\#"),
            '_' => out.push_str("\\_"),
            '%' => out.push_str("\\%"),
            '^' => out.push_str("\\textasciicircum{}"),
            '~' => out.push_str("\\textasciitilde{}"),
            '<' => out.push_str("\\textless{}"),
            '>' => out.push_str("\\textgreater{}"),
            _ => out.push(c),
        }
    }
    out
}

fn n(x: f64) -> String {
    let r = (x * 100.0).round() / 100.0;
    if r == r.trunc() {
        format!("{}", r as i64)
    } else {
        format!("{r}")
    }
}

fn p(x: f64, y: f64) -> String {
    format!("({},{})", n(x), n(y))
}

fn box_style(s: BoxStyle) -> &'static str {
    match s {
        BoxStyle::Solid => "seqsolid",
        BoxStyle::Admission => "seqadmission",
        BoxStyle::Cached => "seqcached",
        BoxStyle::Fits => "seqfits",
        BoxStyle::Enclosure => "seqenclosure",
        BoxStyle::Body => "seqbody",
    }
}

fn edge_style(s: EdgeStyle) -> &'static str {
    match s {
        EdgeStyle::Flow => "seqflow",
        EdgeStyle::Back => "seqback",
        EdgeStyle::Relation => "seqrelation",
        EdgeStyle::Grow => "seqgrow",
    }
}

const PREAMBLE: &str = r#"% Generated by `seq-lang draw --format tikz`. Do not edit by hand.
% Requires \usepackage{tikz}.
\definecolor{seqink}{HTML}{1D2021}
\definecolor{seqdim}{HTML}{6B7280}
\definecolor{seqline}{HTML}{4B5563}
\definecolor{seqfill}{HTML}{EEF2F5}
\definecolor{seqtint}{HTML}{D8E6E4}
\definecolor{seqcache}{HTML}{E6E2DA}
"#;

const STYLES: &str = r#"x=1pt, y=-1pt, line cap=round, line join=round,
  every node/.style={inner sep=0pt, outer sep=0pt, text=seqink},
  seqsolid/.style={draw=seqline, fill=seqfill, line width=.8pt},
  seqbody/.style={draw=seqline, fill=seqfill, line width=.8pt},
  seqadmission/.style={draw=seqline, fill=seqfill, line width=.8pt, dash pattern=on 4pt off 2.5pt},
  seqcached/.style={draw=none, fill=seqcache},
  seqfits/.style={draw=seqdim, line width=.5pt, dash pattern=on 1.5pt off 2.5pt},
  seqenclosure/.style={draw=seqdim, line width=.7pt, dash pattern=on 4.5pt off 3pt},
  seqstation/.style={draw=seqline, fill=seqtint, line width=.9pt},
  seqcell/.style={draw=seqline, fill=white, line width=.5pt},
  seqrail/.style={draw=seqline, line width=.7pt},
  seqflow/.style={draw=seqline, line width=.9pt, ->},
  seqback/.style={draw=seqline, line width=.8pt, dash pattern=on 3pt off 2.5pt, ->},
  seqrelation/.style={draw=seqdim, line width=.7pt, dash pattern=on 1.5pt off 2.5pt, ->},
  seqgrow/.style={draw=seqline, line width=.7pt, ->}"#;

/// Render a figure as a `tikzpicture`, with the colours it needs.
pub fn render(f: &Figure) -> String {
    let mut s = String::from(PREAMBLE);
    let _ = writeln!(s, "\\begin{{tikzpicture}}[{STYLES}]");

    for item in &f.items {
        match item {
            Item::Box { rect, style, round } => {
                let r = if *round > 0.0 {
                    format!("rounded corners={}pt, ", n(*round))
                } else {
                    String::new()
                };
                let _ = writeln!(
                    s,
                    "  \\draw[{r}{}] {} rectangle {};",
                    box_style(*style),
                    p(rect.x, rect.y),
                    p(rect.right(), rect.bottom())
                );
            }
            Item::Poly { pts, style } => {
                let path: Vec<String> = pts.iter().map(|q| p(q.x, q.y)).collect();
                let _ = writeln!(
                    s,
                    "  \\draw[{}] {} -- cycle;",
                    box_style(*style),
                    path.join(" -- ")
                );
            }
            Item::Station { rect, kind, text } => {
                let c = rect.centre();
                match kind {
                    StationKind::Fifo | StationKind::Ps => {
                        let _ = writeln!(
                            s,
                            "  \\draw[seqstation] {} circle ({}pt);",
                            p(c.x, c.y),
                            n(rect.h.min(rect.w) / 2.0)
                        );
                    }
                    StationKind::Delay => {
                        let _ = writeln!(
                            s,
                            "  \\draw[seqstation, rounded corners=8pt] {} rectangle {};",
                            p(rect.x, rect.y),
                            p(rect.right(), rect.bottom())
                        );
                        for k in 0..5 {
                            let x = rect.x + rect.w * (k as f64 + 1.0) / 6.0;
                            let _ = writeln!(s, "  \\draw[seqcell] {} circle (4pt);", p(x, c.y));
                        }
                    }
                    StationKind::Step => {
                        let _ = writeln!(
                            s,
                            "  \\draw[seqstation, rounded corners=3pt] {} rectangle {};",
                            p(rect.x, rect.y),
                            p(rect.right(), rect.bottom())
                        );
                        let (bx, by, bw, bh) =
                            (rect.x + 8.0, rect.bottom() - 13.0, rect.w - 16.0, 6.0);
                        let _ = writeln!(
                            s,
                            "  \\draw[seqcell] {} rectangle {};",
                            p(bx, by),
                            p(bx + bw, by + bh)
                        );
                        let _ = writeln!(
                            s,
                            "  \\draw[seqsolid] {} rectangle {};",
                            p(bx, by),
                            p(bx + bw * 0.62, by + bh)
                        );
                    }
                }
                if !text.is_empty() {
                    let dy = if *kind == StationKind::Step {
                        -8.0
                    } else {
                        0.0
                    };
                    let _ = writeln!(
                        s,
                        "  \\node[anchor=center] at {} {{\\ttfamily\\footnotesize {}}};",
                        p(c.x, c.y + dy),
                        esc(text)
                    );
                }
            }
            Item::Queue { rect, cells } => {
                let _ = writeln!(
                    s,
                    "  \\draw[seqrail] {} -- {};",
                    p(rect.x, rect.y),
                    p(rect.right(), rect.y)
                );
                let _ = writeln!(
                    s,
                    "  \\draw[seqrail] {} -- {};",
                    p(rect.x, rect.bottom()),
                    p(rect.right(), rect.bottom())
                );
                let cw = rect.w / (*cells as f64 + 0.5);
                for k in 0..*cells {
                    let x = rect.x + cw * (k as f64 + 0.25);
                    let _ = writeln!(
                        s,
                        "  \\draw[seqcell] {} rectangle {};",
                        p(x, rect.y + 2.0),
                        p(x + cw * 0.7, rect.bottom() - 2.0)
                    );
                }
            }
            Item::Slots { rect, cols, rows } => {
                let cw = rect.w / *cols as f64;
                let ch = rect.h / *rows as f64;
                for r in 0..*rows {
                    for c in 0..*cols {
                        let (x, y) = (rect.x + cw * c as f64, rect.y + ch * r as f64);
                        let _ = writeln!(
                            s,
                            "  \\draw[seqcell] {} rectangle {};",
                            p(x, y),
                            p(x + cw * 0.82, y + ch * 0.78)
                        );
                    }
                }
            }
            Item::Edge { pts, style, arrow } => {
                let path: Vec<String> = pts.iter().map(|q| p(q.x, q.y)).collect();
                let st = edge_style(*style);
                let opts = if *arrow {
                    st.to_string()
                } else {
                    format!("{st}, -")
                };
                let _ = writeln!(s, "  \\draw[{opts}] {};", path.join(" -- "));
            }
            Item::Text {
                at,
                text,
                anchor,
                size,
                dim,
            } => {
                let a = match anchor {
                    Anchor::Start => "base west",
                    Anchor::Middle => "base",
                    Anchor::End => "base east",
                };
                let sz = match size {
                    crate::figure::TextSize::Title => "\\small",
                    crate::figure::TextSize::Normal => "\\footnotesize",
                    crate::figure::TextSize::Small => "\\scriptsize",
                };
                let colour = if *dim { "text=seqdim, " } else { "" };
                let _ = writeln!(
                    s,
                    "  \\node[{colour}anchor={a}] at {} {{\\ttfamily{sz} {}}};",
                    p(at.x, at.y),
                    esc(text)
                );
            }
        }
    }
    s.push_str("\\end{tikzpicture}\n");
    s
}
